# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 955d0c8cce864d6cc7ce0a1378bf7191561d826cbd674f985dd666a948d30cac59c1e143b42ebaa49d1a2503ab6b088b86e23b9dc79c74bdb6ca5ffd605a0c5f

test:
  secret_key_base: 8b7274cd9c2ceefa9210c90aec456cbb9bd39bbe02f0bd64352beeb44a66570eac3de1c35367406e4a5b1cc59886e1c57c8f2d4e372cbc7d7e593217079bb785

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
